### List all messages
GET http://localhost:3000/messages
Accept: application/json

### Create a new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "test"
}

### Get one single message
GET http://localhost:3000/messages/123
Accept: application/json

### Invalid
GET http://localhost:3000/messages1
Accept: application/json