### List all messages
GET http://localhost:3000/messages
Accept: application/json

### Create a new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "Hello Hua"
}

### Get one single message
GET http://localhost:3000/messages/210
Accept: application/json

### Invalid
GET http://localhost:3000/messages1
Accept: application/json