### Signup
POST http://localhost:3000/reports
content-type: application/json

{
  "make": "volvo",
  "model": "s90",
  "year": 2019,
  "mileage": 27000,
  "lng": 0,
  "lat": 0,
  "price": 200000
}

### Find currently signed user
PATCH http://localhost:3000/reports/1
content-type: application/json

{
  "approved": true
}

### Get an estimation for an existing vehicle
GET http://localhost:3000/reports?make=volvo&model=s90&lat=0&lng=0&mileage=27000&year=2019
content-type: application/json

{
  "approved": true
}

